[package]
name = "lxd_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core","compiler_builtins"]

[dependencies]
bootloader = "0.9.23"
